-- Correção idempotente de perfis, vínculos de clubes e permissões.
-- Pode ser executado novamente no SQL Editor do Supabase (como proprietário do projeto).

begin;

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  nome text not null,
  role text not null check (role in ('admin', 'dono')),
  clube_id bigint references public.clubes(id)
);

create table if not exists public.draft_estado (
  id smallint primary key default 1 check (id = 1),
  iniciado boolean not null default false,
  ordem_clubes bigint[] not null default '{}',
  posicao_atual integer not null default 0,
  atualizado_em timestamptz not null default now()
);

create table if not exists public.draft_contratacoes (
  id bigint generated by default as identity primary key,
  jogador_id bigint not null references public.jogadores(id) on delete cascade,
  jogador_nome text not null,
  clube_id bigint not null references public.clubes(id) on delete cascade,
  valor numeric not null check (valor >= 0),
  rodada integer not null,
  criado_em timestamptz not null default now(),
  unique (jogador_id)
);

-- Bancos criados pela primeira versão podem ter a tabela de transferências
-- incompleta. Estas colunas são usadas pelas propostas de compra/troca.
alter table public.transferencias add column if not exists tipo text not null default 'compra';
alter table public.transferencias add column if not exists jogador_troca_id bigint references public.jogadores(id);
alter table public.transferencias add column if not exists status text not null default 'pendente';
alter table public.transferencias add column if not exists mensagem text not null default '';
alter table public.transferencias add column if not exists data date not null default current_date;

insert into public.draft_estado (id) values (1)
on conflict (id) do nothing;

alter table public.usuarios enable row level security;
alter table public.clubes enable row level security;
alter table public.jogadores enable row level security;
alter table public.jogos enable row level security;
alter table public.estatisticas enable row level security;
alter table public.transferencias enable row level security;
alter table public.noticias enable row level security;
alter table public.draft_estado enable row level security;
alter table public.draft_contratacoes enable row level security;

-- Garante que os dez clubes iniciais existam antes de associar os perfis.
-- OVERRIDING SYSTEM VALUE também funciona quando id é uma identity column.
insert into public.clubes (id, nome, cor_principal, orcamento)
overriding system value
values
  (1, 'Fênix FC', '#FF4500', 100000000),
  (2, 'Trovão Azul', '#1E90FF', 100000000),
  (3, 'Leões da Vila', '#FFD700', 100000000),
  (4, 'Águias Negras', '#2F2F2F', 100000000),
  (5, 'Dragões Vermelhos', '#DC143C', 100000000),
  (6, 'Tubarões FC', '#00CED1', 100000000),
  (7, 'Guerreiros FC', '#228B22', 100000000),
  (8, 'Corsários', '#8B0000', 100000000),
  (9, 'Tornado FC', '#9400D3', 100000000),
  (10, 'Panteras FC', '#FF69B4', 100000000)
on conflict (id) do update set
  nome = excluded.nome,
  cor_principal = excluded.cor_principal,
  orcamento = coalesce(public.clubes.orcamento, excluded.orcamento);

-- Cargas iniciais com IDs explícitos não avançam as sequences automaticamente.
-- Isso fazia novos clubes, jogadores, propostas ou jogos reutilizarem IDs.
do $$
declare
  tabela text;
  tabela_sequence text;
  maior_id bigint;
begin
  foreach tabela in array array[
    'clubes', 'jogadores', 'jogos', 'estatisticas',
    'transferencias', 'noticias', 'draft_contratacoes'
  ]
  loop
    tabela_sequence := pg_get_serial_sequence('public.' || tabela, 'id');
    if tabela_sequence is not null then
      execute format('select max(id)::bigint from public.%I', tabela)
      into maior_id;
      if maior_id is not null then
        perform setval(tabela_sequence::regclass, maior_id, true);
      end if;
    end if;
  end loop;
end;
$$;

-- Cria/atualiza perfis para os usuários que já existem no Supabase Auth.
-- Para as contas conhecidas, o clube é derivado do e-mail; vínculos manuais
-- existentes são preservados quando não há um clube conhecido no mapeamento.
with perfis_auth as (
  select
    u.id,
    u.email,
    coalesce(nullif(u.raw_user_meta_data ->> 'nome', ''), split_part(u.email, '@', 1)) as nome,
    case
      when lower(u.email) = 'admin@resenleirao.com' then 'admin'
      when u.raw_app_meta_data ->> 'role' = 'admin' then 'admin'
      else 'dono'
    end as role,
    case lower(u.email)
      when 'leo@resenleirao.com' then 1
      when 'felipe@resenleirao.com' then 2
      when 'diego@resenleirao.com' then 3
      when 'pedro@resenleirao.com' then 4
      when 'berenguer@resenleirao.com' then 5
      when 'bruno@resenleirao.com' then 6
      when 'yves@resenleirao.com' then 7
      when 'adriano@resenleirao.com' then 8
      when 'jhonny@resenleirao.com' then 9
      when 'piscina@resenleirao.com' then 10
      else null
    end::bigint as clube_id
  from auth.users u
)
insert into public.usuarios as perfil (id, email, nome, role, clube_id)
select id, email, nome, role, clube_id
from perfis_auth
on conflict (id) do update set
  email = excluded.email,
  nome = coalesce(nullif(perfil.nome, ''), excluded.nome),
  role = case
    when excluded.role = 'admin' then 'admin'
    else coalesce(perfil.role, excluded.role)
  end,
  clube_id = coalesce(excluded.clube_id, perfil.clube_id);

-- Mantém os dois lados do relacionamento consistentes. O frontend lê ambos e
-- as políticas de escrita usam clubes.usuario_dono_id.
update public.clubes c
set usuario_dono_id = null
from public.usuarios u
where c.usuario_dono_id = u.id
  and u.clube_id is not null
  and c.id <> u.clube_id;

update public.clubes c
set usuario_dono_id = u.id
from public.usuarios u
where u.clube_id = c.id
  and c.usuario_dono_id is distinct from u.id;

create or replace function public.criar_perfil_novo_usuario()
returns trigger
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  novo_role text;
  novo_clube_id bigint;
begin
  novo_role := case
    when lower(new.email) = 'admin@resenleirao.com' then 'admin'
    when new.raw_app_meta_data ->> 'role' = 'admin' then 'admin'
    else 'dono'
  end;

  novo_clube_id := case lower(new.email)
    when 'leo@resenleirao.com' then 1
    when 'felipe@resenleirao.com' then 2
    when 'diego@resenleirao.com' then 3
    when 'pedro@resenleirao.com' then 4
    when 'berenguer@resenleirao.com' then 5
    when 'bruno@resenleirao.com' then 6
    when 'yves@resenleirao.com' then 7
    when 'adriano@resenleirao.com' then 8
    when 'jhonny@resenleirao.com' then 9
    when 'piscina@resenleirao.com' then 10
    else null
  end;

  insert into public.usuarios (id, email, nome, role, clube_id)
  values (
    new.id,
    new.email,
    coalesce(nullif(new.raw_user_meta_data ->> 'nome', ''), split_part(new.email, '@', 1)),
    novo_role,
    novo_clube_id
  )
  on conflict (id) do update set email = excluded.email;

  if novo_clube_id is not null then
    update public.clubes
    set usuario_dono_id = new.id
    where id = novo_clube_id;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_resenleirao on auth.users;
create trigger on_auth_user_created_resenleirao
  after insert on auth.users
  for each row execute function public.criar_perfil_novo_usuario();

create or replace function public.usuario_eh_admin()
returns boolean
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select exists (
    select 1 from public.usuarios
    where id = auth.uid() and role = 'admin'
  );
$$;

-- O painel usa RPCs security definer para listar donos e alterar os dois lados
-- do vínculo em uma única transação, sem liberar clube_id para updates comuns.
create or replace function public.admin_listar_donos()
returns table (
  id uuid,
  email text,
  nome text,
  role text,
  clube_id bigint
)
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select u.id, u.email, u.nome, u.role, u.clube_id
  from public.usuarios u
  where public.usuario_eh_admin()
    and u.role = 'dono'
  order by u.nome, u.email;
$$;

create or replace function public.admin_associar_clube_dono(
  p_clube_id bigint,
  p_usuario_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
begin
  if not public.usuario_eh_admin() then
    raise exception 'Acesso restrito ao administrador'
      using errcode = '42501';
  end if;

  if not exists (select 1 from public.clubes where id = p_clube_id) then
    raise exception 'Clube não encontrado';
  end if;

  if p_usuario_id is not null and not exists (
    select 1 from public.usuarios
    where id = p_usuario_id and role = 'dono'
  ) then
    raise exception 'Perfil de dono não encontrado';
  end if;

  -- Libera o dono anterior deste clube e o clube anterior do novo dono.
  update public.usuarios
  set clube_id = null
  where clube_id = p_clube_id;

  if p_usuario_id is not null then
    update public.clubes
    set usuario_dono_id = null
    where usuario_dono_id = p_usuario_id;
  end if;

  update public.clubes
  set usuario_dono_id = p_usuario_id
  where id = p_clube_id;

  if p_usuario_id is not null then
    update public.usuarios
    set clube_id = p_clube_id
    where id = p_usuario_id;
  end if;
end;
$$;

create or replace function public.admin_iniciar_draft(p_ordem_clubes bigint[])
returns void
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  total_clubes integer;
begin
  if not public.usuario_eh_admin() then
    raise exception 'Apenas o administrador pode iniciar o draft'
      using errcode = '42501';
  end if;

  select count(*) into total_clubes from public.clubes;
  if total_clubes < 2
    or cardinality(p_ordem_clubes) <> total_clubes
    or (
      select count(distinct clube_id)
      from unnest(p_ordem_clubes) as ordem(clube_id)
    ) <> total_clubes
    or exists (
      select 1 from unnest(p_ordem_clubes) as ordem(clube_id)
      where not exists (select 1 from public.clubes c where c.id = clube_id)
    )
  then
    raise exception 'A ordem do draft deve conter todos os clubes uma única vez';
  end if;

  -- A condição explícita também funciona em bancos com proteção contra DELETE sem WHERE.
  delete from public.draft_contratacoes where id is not null;
  update public.draft_estado
  set iniciado = true,
      ordem_clubes = p_ordem_clubes,
      posicao_atual = 0,
      atualizado_em = now()
  where id = 1;
end;
$$;

create or replace function public.draft_contratar_jogador(
  p_nome text,
  p_posicao text,
  p_valor numeric
)
returns void
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  estado public.draft_estado%rowtype;
  clube_atual_id bigint;
  jogador_id_criado bigint;
  numero_disponivel integer;
  orcamento_restante numeric;
begin
  select * into estado
  from public.draft_estado
  where id = 1
  for update;

  if not estado.iniciado then
    raise exception 'O draft não está iniciado';
  end if;

  clube_atual_id := estado.ordem_clubes[estado.posicao_atual + 1];
  if clube_atual_id is null then
    raise exception 'Posição atual do draft inválida';
  end if;

  if not public.usuario_eh_admin() and not exists (
    select 1 from public.clubes
    where id = clube_atual_id and usuario_dono_id = auth.uid()
  ) then
    raise exception 'Não é a vez do seu clube'
      using errcode = '42501';
  end if;

  if nullif(trim(p_nome), '') is null
    or p_posicao not in ('Goleiro', 'Zagueiro', 'Lateral', 'Meio-Campo', 'Atacante')
    or p_valor < 0
  then
    raise exception 'Dados do jogador inválidos';
  end if;

  select c.orcamento - coalesce(sum(dc.valor), 0)
  into orcamento_restante
  from public.clubes c
  left join public.draft_contratacoes dc on dc.clube_id = c.id
  where c.id = clube_atual_id
  group by c.orcamento;

  if p_valor > orcamento_restante then
    raise exception 'Orçamento insuficiente';
  end if;

  select numero into numero_disponivel
  from generate_series(1, 99) as numeros(numero)
  where not exists (
    select 1 from public.jogadores j
    where j.clube_id = clube_atual_id and j.numero = numero
  )
  order by numero
  limit 1;

  if numero_disponivel is null then
    raise exception 'O clube não possui número de camisa disponível';
  end if;

  insert into public.jogadores (
    nome, posicao, numero, clube_id, foto_url, status,
    valor_mercado, jogos_suspensao
  ) values (
    trim(p_nome), p_posicao, numero_disponivel, clube_atual_id, null, 'ativo',
    p_valor, 0
  ) returning id into jogador_id_criado;

  insert into public.draft_contratacoes (
    jogador_id, jogador_nome, clube_id, valor, rodada
  ) values (
    jogador_id_criado, trim(p_nome), clube_atual_id, p_valor,
    estado.posicao_atual + 1
  );

  update public.draft_estado
  set posicao_atual = estado.posicao_atual + 1,
      iniciado = estado.posicao_atual + 1 < cardinality(estado.ordem_clubes),
      atualizado_em = now()
  where id = 1;
end;
$$;

create or replace function public.criar_proposta_transferencia(
  p_jogador_id bigint,
  p_clube_destino_id bigint,
  p_valor numeric,
  p_tipo text,
  p_jogador_troca_id bigint default null,
  p_mensagem text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  clube_origem_id bigint;
  proposta_id bigint;
  orcamento_destino numeric;
begin
  select clube_id into clube_origem_id
  from public.jogadores
  where id = p_jogador_id and status in ('ativo', 'suspenso');

  if clube_origem_id is null or clube_origem_id = p_clube_destino_id then
    raise exception 'Jogador indisponível para transferência';
  end if;

  if not public.usuario_eh_admin() and not exists (
    select 1 from public.clubes
    where id = p_clube_destino_id and usuario_dono_id = auth.uid()
  ) then
    raise exception 'Você não representa o clube comprador'
      using errcode = '42501';
  end if;

  select orcamento into orcamento_destino
  from public.clubes where id = p_clube_destino_id;
  if p_valor < 0 or p_valor > orcamento_destino then
    raise exception 'Orçamento insuficiente';
  end if;

  if p_jogador_troca_id is not null and not exists (
    select 1 from public.jogadores
    where id = p_jogador_troca_id and clube_id = p_clube_destino_id
  ) then
    raise exception 'Jogador oferecido na troca não pertence ao clube comprador';
  end if;

  insert into public.transferencias (
    jogador_id, clube_origem_id, clube_destino_id, valor, tipo,
    jogador_troca_id, data, status, mensagem
  ) values (
    p_jogador_id, clube_origem_id, p_clube_destino_id, p_valor, p_tipo,
    p_jogador_troca_id, current_date, 'pendente', coalesce(p_mensagem, '')
  ) returning id into proposta_id;

  return proposta_id;
end;
$$;

create or replace function public.aceitar_proposta_transferencia(p_transferencia_id bigint)
returns void
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  proposta public.transferencias%rowtype;
  orcamento_comprador numeric;
begin
  select * into proposta
  from public.transferencias
  where id = p_transferencia_id
  for update;

  if proposta.id is null or proposta.status <> 'pendente' then
    raise exception 'Proposta não encontrada ou já respondida';
  end if;

  if not public.usuario_eh_admin() and not exists (
    select 1 from public.clubes
    where id = proposta.clube_origem_id and usuario_dono_id = auth.uid()
  ) then
    raise exception 'Apenas o clube vendedor pode aceitar a proposta'
      using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.jogadores
    where id = proposta.jogador_id and clube_id = proposta.clube_origem_id
  ) then
    raise exception 'O jogador não pertence mais ao clube vendedor';
  end if;

  select orcamento into orcamento_comprador
  from public.clubes where id = proposta.clube_destino_id
  for update;
  if proposta.valor > orcamento_comprador then
    raise exception 'O clube comprador não possui orçamento suficiente';
  end if;

  if proposta.jogador_troca_id is not null then
    update public.jogadores
    set clube_id = proposta.clube_origem_id
    where id = proposta.jogador_troca_id
      and clube_id = proposta.clube_destino_id;
    if not found then
      raise exception 'O jogador oferecido na troca não está mais disponível';
    end if;
  end if;

  update public.jogadores
  set clube_id = proposta.clube_destino_id
  where id = proposta.jogador_id;

  if proposta.valor > 0 then
    update public.clubes
    set orcamento = orcamento + proposta.valor
    where id = proposta.clube_origem_id;
    update public.clubes
    set orcamento = orcamento - proposta.valor
    where id = proposta.clube_destino_id;
  end if;

  update public.transferencias
  set status = 'aceita'
  where id = p_transferencia_id;
end;
$$;

create or replace function public.rejeitar_proposta_transferencia(p_transferencia_id bigint)
returns void
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  proposta public.transferencias%rowtype;
begin
  select * into proposta
  from public.transferencias
  where id = p_transferencia_id
  for update;

  if proposta.id is null or proposta.status <> 'pendente' then
    raise exception 'Proposta não encontrada ou já respondida';
  end if;

  if not public.usuario_eh_admin() and not exists (
    select 1 from public.clubes
    where id = proposta.clube_origem_id and usuario_dono_id = auth.uid()
  ) then
    raise exception 'Apenas o clube vendedor pode rejeitar a proposta'
      using errcode = '42501';
  end if;

  update public.transferencias set status = 'rejeitada'
  where id = p_transferencia_id;
end;
$$;

create or replace function public.admin_gerar_jogos()
returns integer
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  times bigint[];
  quantidade integer;
  rodada integer;
  partida integer;
  clube_casa bigint;
  clube_fora bigint;
  total_criado integer := 0;
begin
  if not public.usuario_eh_admin() then
    raise exception 'Apenas o administrador pode gerar os jogos'
      using errcode = '42501';
  end if;

  if exists (select 1 from public.jogos where fase = 'grupos') then
    raise exception 'Os jogos da fase de grupos já foram gerados';
  end if;

  select array_agg(id order by id) into times from public.clubes;
  if coalesce(cardinality(times), 0) < 2 then
    raise exception 'Cadastre pelo menos dois clubes';
  end if;

  if cardinality(times) % 2 = 1 then
    times := array_append(times, null::bigint);
  end if;
  quantidade := cardinality(times);

  for rodada in 1..(quantidade - 1) loop
    for partida in 1..(quantidade / 2) loop
      clube_casa := times[partida];
      clube_fora := times[quantidade - partida + 1];
      if clube_casa is not null and clube_fora is not null then
        insert into public.jogos (
          clube_casa_id, clube_fora_id, gols_casa, gols_fora,
          rodada, fase, data, status
        ) values (
          clube_casa, clube_fora, null, null, rodada, 'grupos',
          current_date + ((rodada - 1) * 7), 'agendado'
        );
        -- Segundo turno: os mesmos confrontos com mando invertido.
        insert into public.jogos (
          clube_casa_id, clube_fora_id, gols_casa, gols_fora,
          rodada, fase, data, status
        ) values (
          clube_fora, clube_casa, null, null, rodada + (quantidade - 1), 'grupos',
          current_date + ((rodada + quantidade - 2) * 7), 'agendado'
        );
        total_criado := total_criado + 2;
      end if;
    end loop;

    times := array[times[1], times[quantidade]] || times[2:(quantidade - 1)];
  end loop;

  return total_criado;
end;
$$;

-- Limpa somente a competição: resultados e estatísticas. Clubes, donos, elencos,
-- valores de mercado, transferências e o histórico do draft são preservados.
create or replace function public.admin_resetar_competicao()
returns void
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
begin
  if not public.usuario_eh_admin() then
    raise exception 'Apenas o administrador pode limpar a competição' using errcode = '42501';
  end if;

  delete from public.estatisticas where id is not null;
  delete from public.jogos where id is not null;
end;
$$;

revoke all on function public.admin_listar_donos() from public;
revoke all on function public.admin_associar_clube_dono(bigint, uuid) from public;
grant execute on function public.admin_listar_donos() to authenticated;
grant execute on function public.admin_associar_clube_dono(bigint, uuid) to authenticated;
revoke all on function public.admin_iniciar_draft(bigint[]) from public;
revoke all on function public.draft_contratar_jogador(text, text, numeric) from public;
revoke all on function public.criar_proposta_transferencia(bigint, bigint, numeric, text, bigint, text) from public;
revoke all on function public.aceitar_proposta_transferencia(bigint) from public;
revoke all on function public.rejeitar_proposta_transferencia(bigint) from public;
revoke all on function public.admin_gerar_jogos() from public;
revoke all on function public.admin_resetar_competicao() from public;
grant execute on function public.admin_iniciar_draft(bigint[]) to authenticated;
grant execute on function public.draft_contratar_jogador(text, text, numeric) to authenticated;
grant execute on function public.criar_proposta_transferencia(bigint, bigint, numeric, text, bigint, text) to authenticated;
grant execute on function public.aceitar_proposta_transferencia(bigint) to authenticated;
grant execute on function public.rejeitar_proposta_transferencia(bigint) to authenticated;
grant execute on function public.admin_gerar_jogos() to authenticated;
grant execute on function public.admin_resetar_competicao() to authenticated;

-- Remove também políticas antigas com nomes não previstos. Uma política
-- residual em usuarios era suficiente para reintroduzir recursão em todo app.
do $$
declare
  politica record;
begin
  for politica in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = any (array[
        'usuarios', 'clubes', 'jogadores', 'jogos', 'estatisticas',
        'transferencias', 'noticias', 'draft_estado', 'draft_contratacoes'
      ])
  loop
    execute format(
      'drop policy %I on %I.%I',
      politica.policyname,
      politica.schemaname,
      politica.tablename
    );
  end loop;
end;
$$;

-- Impede que um usuário comum se promova para admin ou troque o próprio clube.
revoke update on public.usuarios from authenticated;
grant update (nome) on public.usuarios to authenticated;

-- As permissões de tabela são filtradas pelas políticas RLS abaixo.
grant select on public.usuarios to authenticated;
grant select on public.clubes, public.jogadores, public.jogos,
  public.estatisticas, public.transferencias, public.noticias,
  public.draft_estado, public.draft_contratacoes to anon, authenticated;
grant insert, update, delete on public.clubes, public.jogadores, public.jogos,
  public.estatisticas, public.transferencias, public.noticias to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Usuários podem ver seus próprios dados" on public.usuarios;
drop policy if exists "Usuários podem atualizar seus próprios dados" on public.usuarios;
drop policy if exists "Usuarios podem ler o proprio perfil" on public.usuarios;
drop policy if exists "Usuarios podem atualizar o proprio nome" on public.usuarios;
create policy "Usuarios podem ler o proprio perfil"
  on public.usuarios for select
  using (auth.uid() = id);
create policy "Usuarios podem atualizar o proprio nome"
  on public.usuarios for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Clubes são visíveis para todos" on public.clubes;
drop policy if exists "Donos podem atualizar seus clubes" on public.clubes;
drop policy if exists "Clubes podem ser lidos" on public.clubes;
drop policy if exists "Admin gerencia clubes" on public.clubes;
drop policy if exists "Dono atualiza seu clube" on public.clubes;
create policy "Clubes podem ser lidos" on public.clubes for select using (true);
create policy "Admin gerencia clubes" on public.clubes for all
  using (public.usuario_eh_admin()) with check (public.usuario_eh_admin());
create policy "Dono atualiza seu clube" on public.clubes for update
  using (auth.uid() = usuario_dono_id)
  with check (auth.uid() = usuario_dono_id);

drop policy if exists "Jogadores são visíveis para todos" on public.jogadores;
drop policy if exists "Donos podem gerenciar jogadores de seus clubes" on public.jogadores;
drop policy if exists "Jogadores podem ser lidos" on public.jogadores;
drop policy if exists "Admin e dono gerenciam jogadores" on public.jogadores;
create policy "Jogadores podem ser lidos" on public.jogadores for select using (true);
create policy "Admin e dono gerenciam jogadores" on public.jogadores for all
  using (
    public.usuario_eh_admin()
    or exists (select 1 from public.clubes c where c.id = clube_id and c.usuario_dono_id = auth.uid())
  )
  with check (
    public.usuario_eh_admin()
    or exists (select 1 from public.clubes c where c.id = clube_id and c.usuario_dono_id = auth.uid())
  );

drop policy if exists "Jogos são visíveis para todos" on public.jogos;
drop policy if exists "Admin pode gerenciar jogos" on public.jogos;
drop policy if exists "Jogos podem ser lidos" on public.jogos;
drop policy if exists "Admin gerencia jogos" on public.jogos;
create policy "Jogos podem ser lidos" on public.jogos for select using (true);
create policy "Admin gerencia jogos" on public.jogos for all
  using (public.usuario_eh_admin()) with check (public.usuario_eh_admin());

drop policy if exists "Estatísticas são visíveis para todos" on public.estatisticas;
drop policy if exists "Admin pode gerenciar estatísticas" on public.estatisticas;
drop policy if exists "Estatisticas podem ser lidas" on public.estatisticas;
drop policy if exists "Admin gerencia estatisticas" on public.estatisticas;
create policy "Estatisticas podem ser lidas" on public.estatisticas for select using (true);
create policy "Admin gerencia estatisticas" on public.estatisticas for all
  using (public.usuario_eh_admin()) with check (public.usuario_eh_admin());

drop policy if exists "Transferências são visíveis para todos" on public.transferencias;
drop policy if exists "Donos podem gerenciar transferências" on public.transferencias;
drop policy if exists "Transferencias podem ser lidas" on public.transferencias;
drop policy if exists "Admin e donos gerenciam transferencias" on public.transferencias;
create policy "Transferencias podem ser lidas" on public.transferencias for select using (true);
create policy "Comprador cria propostas" on public.transferencias for insert
  with check (
    public.usuario_eh_admin()
    or exists (
      select 1 from public.clubes c
      where c.usuario_dono_id = auth.uid()
        and c.id = clube_destino_id
    )
  );

drop policy if exists "Estado do draft pode ser lido" on public.draft_estado;
drop policy if exists "Contratacoes do draft podem ser lidas" on public.draft_contratacoes;
create policy "Estado do draft pode ser lido" on public.draft_estado for select using (true);
create policy "Contratacoes do draft podem ser lidas" on public.draft_contratacoes for select using (true);

drop policy if exists "Notícias são visíveis para todos" on public.noticias;
drop policy if exists "Donos podem gerenciar notícias de seus clubes" on public.noticias;
drop policy if exists "Noticias podem ser lidas" on public.noticias;
drop policy if exists "Admin e dono gerenciam noticias" on public.noticias;
create policy "Noticias podem ser lidas" on public.noticias for select using (true);
create policy "Admin e dono gerenciam noticias" on public.noticias for all
  using (
    public.usuario_eh_admin()
    or exists (select 1 from public.clubes c where c.id = clube_id and c.usuario_dono_id = auth.uid())
  )
  with check (
    public.usuario_eh_admin()
    or exists (select 1 from public.clubes c where c.id = clube_id and c.usuario_dono_id = auth.uid())
  );

commit;
