-- Migração de correção do Resenleirão
-- Execute este arquivo UMA VEZ no SQL Editor do Supabase, depois do setup-completo.sql.
-- Ele é seguro para executar novamente e preserva resultados já lançados.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Corrige defaults que impediam inserções feitas pelo aplicativo.
-- Algumas instalações já usam IDENTITY; nesse caso o próprio banco já gera o ID.
DO $$
DECLARE item record;
BEGIN
  FOR item IN
    SELECT c.relname AS tabela, a.attname AS coluna, a.attidentity, format_type(a.atttypid, a.atttypmod) AS tipo
    FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND a.attnum > 0 AND NOT a.attisdropped
      AND c.relname IN ('jogadores','jogos','estatisticas','transferencias','noticias') AND a.attname = 'id'
  LOOP
    IF item.attidentity = '' AND item.tipo = 'uuid' THEN
      EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id SET DEFAULT gen_random_uuid()', item.tabela);
    END IF;
  END LOOP;
END $$;

DO $$
DECLARE identidade text; possui_default boolean;
BEGIN
  SELECT a.attidentity, (pg_get_expr(d.adbin, d.adrelid) IS NOT NULL)
    INTO identidade, possui_default
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
  WHERE n.nspname = 'public' AND c.relname = 'clubes' AND a.attname = 'id';
  IF identidade = '' AND NOT possui_default THEN
    ALTER TABLE public.clubes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

ALTER TABLE clubes ALTER COLUMN orcamento SET DEFAULT 100000000;
ALTER TABLE jogadores ALTER COLUMN valor_mercado SET DEFAULT 0;
ALTER TABLE jogadores ALTER COLUMN jogos_suspensao SET DEFAULT 0;
ALTER TABLE jogadores ALTER COLUMN status SET DEFAULT 'ativo';
ALTER TABLE jogos ALTER COLUMN status SET DEFAULT 'agendado';
ALTER TABLE transferencias ALTER COLUMN status SET DEFAULT 'pendente';

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.usuarios WHERE id = auth.uid() AND role = 'admin');
$$;

CREATE OR REPLACE FUNCTION public.my_clube_id()
RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT clube_id FROM public.usuarios WHERE id = auth.uid();
$$;

-- Políticas sem subconsulta recursiva e com WITH CHECK (a ausência dele permitia/bloqueava dados indevidamente).
DO $$
DECLARE p record;
BEGIN
  FOR p IN SELECT tablename, policyname FROM pg_policies WHERE schemaname = 'public'
    AND tablename IN ('usuarios','clubes','jogadores','jogos','estatisticas','transferencias','noticias')
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', p.policyname, p.tablename);
  END LOOP;
END $$;

CREATE POLICY "leitura clubes" ON clubes FOR SELECT USING (true);
CREATE POLICY "leitura jogadores" ON jogadores FOR SELECT USING (true);
CREATE POLICY "leitura jogos" ON jogos FOR SELECT USING (true);
CREATE POLICY "leitura estatisticas" ON estatisticas FOR SELECT USING (true);
CREATE POLICY "leitura transferencias" ON transferencias FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "leitura noticias" ON noticias FOR SELECT USING (true);
CREATE POLICY "leitura usuarios" ON usuarios FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Donos podem atualizar seus clubes" ON clubes;
DROP POLICY IF EXISTS "Admin pode gerenciar clubes" ON clubes;
CREATE POLICY "admin gerencia clubes" ON clubes FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Donos podem gerenciar jogadores de seus clubes" ON jogadores;
DROP POLICY IF EXISTS "Admin pode gerenciar jogadores" ON jogadores;
CREATE POLICY "admin gerencia jogadores" ON jogadores FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "dono gerencia elenco proprio" ON jogadores FOR ALL
  USING (clube_id = public.my_clube_id()) WITH CHECK (clube_id = public.my_clube_id());

DROP POLICY IF EXISTS "Admin pode gerenciar jogos" ON jogos;
CREATE POLICY "admin gerencia jogos" ON jogos FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "Admin pode gerenciar estatísticas" ON estatisticas;
CREATE POLICY "admin gerencia estatisticas" ON estatisticas FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Donos podem gerenciar transferências" ON transferencias;
CREATE POLICY "admin gerencia transferencias" ON transferencias FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "clubes veem transferencias envolvidas" ON transferencias FOR SELECT
  USING (clube_origem_id = public.my_clube_id() OR clube_destino_id = public.my_clube_id());

DROP POLICY IF EXISTS "Usuários podem atualizar seus próprios dados" ON usuarios;
DROP POLICY IF EXISTS "Admin pode gerenciar usuários" ON usuarios;
CREATE POLICY "admin gerencia usuarios" ON usuarios FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "usuario atualiza perfil proprio" ON usuarios FOR UPDATE USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Proposta e aceite executados em uma transação no banco. Não confie no navegador para saldo ou propriedade.
CREATE OR REPLACE FUNCTION public.criar_proposta_transferencia(
  p_jogador_id bigint, p_valor bigint, p_tipo text, p_jogador_troca_id bigint DEFAULT NULL, p_mensagem text DEFAULT ''
) RETURNS transferencias LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_origem bigint; v_destino bigint := public.my_clube_id(); v_t transferencias;
BEGIN
  IF v_destino IS NULL THEN RAISE EXCEPTION 'Apenas donos de clube podem enviar propostas'; END IF;
  SELECT clube_id INTO v_origem FROM jogadores WHERE id = p_jogador_id AND status = 'ativo' FOR UPDATE;
  IF v_origem IS NULL OR v_origem = v_destino THEN RAISE EXCEPTION 'Jogador indisponível para negociação'; END IF;
  IF p_valor < 0 OR p_tipo NOT IN ('compra','emprestimo','troca','jogador_mais_valor') THEN RAISE EXCEPTION 'Proposta inválida'; END IF;
  IF p_tipo IN ('troca','jogador_mais_valor') THEN
    IF p_jogador_troca_id IS NULL OR NOT EXISTS (SELECT 1 FROM jogadores WHERE id = p_jogador_troca_id AND clube_id = v_destino AND status = 'ativo') THEN
      RAISE EXCEPTION 'Selecione um jogador ativo do seu elenco para a troca';
    END IF;
  END IF;
  IF p_valor > 0 AND (SELECT orcamento FROM clubes WHERE id = v_destino) < p_valor THEN RAISE EXCEPTION 'Orçamento insuficiente'; END IF;
  INSERT INTO transferencias (jogador_id,clube_origem_id,clube_destino_id,valor,tipo,jogador_troca_id,data,status,mensagem)
  VALUES (p_jogador_id,v_origem,v_destino,p_valor,p_tipo,p_jogador_troca_id,current_date::text,'pendente',coalesce(p_mensagem,'')) RETURNING * INTO v_t;
  RETURN v_t;
END; $$;

CREATE OR REPLACE FUNCTION public.decidir_transferencia(p_transferencia_id bigint, p_aceitar boolean)
RETURNS transferencias LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE t transferencias;
BEGIN
  SELECT * INTO t FROM transferencias WHERE id = p_transferencia_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Proposta não encontrada'; END IF;
  IF NOT public.is_admin() AND t.clube_origem_id <> public.my_clube_id() THEN RAISE EXCEPTION 'Você não pode decidir esta proposta'; END IF;
  IF t.status <> 'pendente' THEN RAISE EXCEPTION 'Esta proposta já foi decidida'; END IF;
  IF NOT p_aceitar THEN UPDATE transferencias SET status='rejeitada' WHERE id=t.id RETURNING * INTO t; RETURN t; END IF;
  IF NOT EXISTS (SELECT 1 FROM jogadores WHERE id=t.jogador_id AND clube_id=t.clube_origem_id AND status='ativo') THEN RAISE EXCEPTION 'O jogador não está mais disponível'; END IF;
  IF t.valor > 0 AND (SELECT orcamento FROM clubes WHERE id=t.clube_destino_id FOR UPDATE) < t.valor THEN RAISE EXCEPTION 'Orçamento insuficiente'; END IF;
  IF t.jogador_troca_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM jogadores WHERE id=t.jogador_troca_id AND clube_id=t.clube_destino_id AND status='ativo') THEN RAISE EXCEPTION 'Jogador de troca indisponível'; END IF;
  UPDATE jogadores SET clube_id=t.clube_destino_id WHERE id=t.jogador_id;
  IF t.jogador_troca_id IS NOT NULL THEN UPDATE jogadores SET clube_id=t.clube_origem_id WHERE id=t.jogador_troca_id; END IF;
  IF t.valor > 0 THEN UPDATE clubes SET orcamento=orcamento-t.valor WHERE id=t.clube_destino_id; UPDATE clubes SET orcamento=orcamento+t.valor WHERE id=t.clube_origem_id; END IF;
  UPDATE transferencias SET status='aceita' WHERE id=t.id RETURNING * INTO t;
  RETURN t;
END; $$;

-- Calendário completo de pontos corridos: para 10 clubes cria 18 rodadas, 90 jogos, ida e volta.
CREATE OR REPLACE FUNCTION public.gerar_calendario_ida_volta(p_substituir boolean DEFAULT false)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE ids bigint[]; n integer; r integer; i integer; a bigint; b bigint; casa bigint; fora bigint; gerados integer := 0;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Apenas o administrador pode gerar o calendário'; END IF;
  IF EXISTS (SELECT 1 FROM jogos WHERE status='realizado') THEN RAISE EXCEPTION 'Há resultados lançados: o calendário não pode ser substituído'; END IF;
  IF EXISTS (SELECT 1 FROM jogos) AND NOT p_substituir THEN RAISE EXCEPTION 'Já existe calendário. Use substituir para recriá-lo'; END IF;
  IF p_substituir THEN DELETE FROM jogos WHERE status='agendado'; END IF;
  SELECT array_agg(id ORDER BY id) INTO ids FROM clubes;
  n := cardinality(ids); IF n IS NULL OR n < 2 OR n % 2 <> 0 THEN RAISE EXCEPTION 'É necessário um número par de pelo menos dois clubes'; END IF;
  FOR r IN 1..n-1 LOOP
    FOR i IN 1..n/2 LOOP
      a := ids[i]; b := ids[n-i+1];
      IF (r+i) % 2 = 0 THEN casa:=a; fora:=b; ELSE casa:=b; fora:=a; END IF;
      INSERT INTO jogos (clube_casa_id,clube_fora_id,rodada,fase,data,status) VALUES (casa,fora,r,'grupos',current_date::text,'agendado');
      INSERT INTO jogos (clube_casa_id,clube_fora_id,rodada,fase,data,status) VALUES (fora,casa,r+n-1,'grupos',current_date::text,'agendado'); gerados := gerados + 2;
    END LOOP;
    ids := ARRAY[ids[1]] || ids[n:2];
  END LOOP;
  RETURN gerados;
END; $$;

-- Draft persistente, com ordem e escolhas compartilhadas entre todos os usuários.
CREATE TABLE IF NOT EXISTS drafts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), status text NOT NULL DEFAULT 'aberto' CHECK(status IN ('aberto','finalizado')), ordem bigint[] NOT NULL, escolha_atual integer NOT NULL DEFAULT 0, criado_em timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS escolhas_draft (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), draft_id uuid NOT NULL REFERENCES drafts ON DELETE CASCADE, clube_id bigint NOT NULL REFERENCES clubes, jogador_id bigint NOT NULL REFERENCES jogadores, valor bigint NOT NULL CHECK(valor >= 0), escolha integer NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), UNIQUE(draft_id, escolha));
ALTER TABLE drafts ENABLE ROW LEVEL SECURITY; ALTER TABLE escolhas_draft ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "leitura draft" ON drafts;
DROP POLICY IF EXISTS "leitura escolhas draft" ON escolhas_draft;
CREATE POLICY "leitura draft" ON drafts FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "leitura escolhas draft" ON escolhas_draft FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE OR REPLACE FUNCTION public.iniciar_draft()
RETURNS drafts LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE d drafts; ordem bigint[];
BEGIN
 IF NOT public.is_admin() THEN RAISE EXCEPTION 'Apenas o administrador inicia o draft'; END IF;
 SELECT array_agg(id ORDER BY random()) INTO ordem FROM clubes;
 IF cardinality(ordem) < 2 THEN RAISE EXCEPTION 'Cadastre ao menos dois clubes'; END IF;
 UPDATE drafts SET status='finalizado' WHERE status='aberto';
 INSERT INTO drafts(ordem) VALUES(ordem) RETURNING * INTO d; RETURN d;
END; $$;

CREATE OR REPLACE FUNCTION public.escolher_no_draft(p_nome text,p_posicao text,p_numero integer,p_valor bigint)
RETURNS jogadores LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE d drafts; clube bigint; j jogadores;
BEGIN
 SELECT * INTO d FROM drafts WHERE status='aberto' ORDER BY criado_em DESC LIMIT 1 FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Não há draft aberto'; END IF;
 clube := d.ordem[d.escolha_atual + 1];
 IF NOT public.is_admin() AND clube <> public.my_clube_id() THEN RAISE EXCEPTION 'Ainda não é a vez do seu clube'; END IF;
 IF coalesce(trim(p_nome),'')='' OR p_posicao NOT IN ('Goleiro','Zagueiro','Lateral','Meio-Campo','Atacante') OR p_numero NOT BETWEEN 1 AND 99 OR p_valor < 0 THEN RAISE EXCEPTION 'Dados do jogador inválidos'; END IF;
 IF (SELECT orcamento FROM clubes WHERE id=clube FOR UPDATE) < p_valor THEN RAISE EXCEPTION 'Orçamento insuficiente'; END IF;
 INSERT INTO jogadores(nome,posicao,numero,clube_id,status,valor_mercado,jogos_suspensao) VALUES(p_nome,p_posicao,p_numero,clube,'ativo',p_valor,0) RETURNING * INTO j;
 UPDATE clubes SET orcamento=orcamento-p_valor WHERE id=clube;
 INSERT INTO escolhas_draft(draft_id,clube_id,jogador_id,valor,escolha) VALUES(d.id,clube,j.id,p_valor,d.escolha_atual+1);
 IF d.escolha_atual+1 >= cardinality(d.ordem) THEN UPDATE drafts SET status='finalizado', escolha_atual=d.escolha_atual+1 WHERE id=d.id; ELSE UPDATE drafts SET escolha_atual=d.escolha_atual+1 WHERE id=d.id; END IF;
 RETURN j;
END; $$;

GRANT EXECUTE ON FUNCTION public.criar_proposta_transferencia(bigint,bigint,text,bigint,text), public.decidir_transferencia(bigint,boolean), public.escolher_no_draft(text,text,integer,bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.gerar_calendario_ida_volta(boolean), public.iniciar_draft() TO authenticated;
